language: python
python:
  - "3.6"
jobs:
  include:
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell 
python: 
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

  
services:
  - docker
virtualenv:
  system_site_packages: true

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
  - pytest